"""
Background Job Framework — extensible scheduler for idle-time background tasks.

Architecture:
  - BackgroundJobRunner (ABC): Base class for individual job types
  - BackgroundJobScheduler: Manages job lifecycle, idle detection, pause/cancel

Phase 1: TTSPreGenJob (tts_pregen_job.py)
Phase 2+: IdeaBoardJob, DataCleanupJob, etc.
"""
import asyncio
import json
import logging
import time
from abc import ABC, abstractmethod
from datetime import datetime

from core.database import get_db_session, BackgroundJobState

logger = logging.getLogger("background_jobs")


class BackgroundJobRunner(ABC):
    """Abstract base class for all background jobs."""
    
    job_name: str = "unnamed_job"
    
    @abstractmethod
    async def get_next_task(self) -> dict | None:
        """Return the next task to execute, or None if nothing to do.
        Priority queue is DYNAMIC — recalculated on every call."""
    
    @abstractmethod
    async def execute_task(self, task: dict) -> bool:
        """Execute a single task. Return True on success, False on failure."""
    
    @abstractmethod
    def get_status(self) -> dict:
        """Return current status for API/monitoring."""


class BackgroundJobScheduler:
    """
    Central scheduler for all background jobs.
    
    Lifecycle: start() runs in lifespan, loops forever:
      1. Check if idle (no on-demand TTS running + cooldown)
      2. Pick next task from registered jobs
      3. Execute with pause/cancel checkpoints every chunk
      4. Persist state to BackgroundJobState table
    
    Signal protocol:
      - request_pause()  → KB3: chat TTS needs Edge TTS, pause pre-gen immediately
      - request_resume() → KB3: chat TTS done, resume pre-gen
      - request_cancel() → KB2: user playing different chapter, cancel pre-gen
      - notify_tts_activity() → any on-demand TTS, update cooldown timer
    """
    
    COOLDOWN_SECONDS = 30
    IDLE_CHECK_INTERVAL = 5    # seconds between idle checks when busy
    SLEEP_INTERVAL = 10        # seconds between checks when no tasks available
    
    def __init__(self):
        self._jobs: list[BackgroundJobRunner] = []
        self._pause_event = asyncio.Event()
        self._pause_event.set()  # default: not paused (set = running)
        self._cancel_event = asyncio.Event()
        self._current_job: BackgroundJobRunner | None = None
        self._current_task: dict | None = None
        self._running = False
        self._last_tts_activity: float = 0.0
        self._generation_tasks_ref: dict | None = None  # set by server.py
        self._pregen_stream = None  # PregenStreamManager, set by server.py
        
    def register_job(self, job: BackgroundJobRunner):
        """Register a background job. Call before start()."""
        self._jobs.append(job)
        logger.debug(f"[SCHEDULER] Registered job: {job.job_name}")
    
    def set_generation_tasks_ref(self, ref: dict):
        """Set reference to server.py's generation_tasks dict for idle detection."""
        self._generation_tasks_ref = ref
    
    def set_pregen_stream(self, stream):
        """Set PregenStreamManager for broadcasting queue updates."""
        self._pregen_stream = stream
    
    def get_active_pregen_chapter(self) -> dict | None:
        """Get the chapter currently being generated by TTSPreGenJob.
        
        Returns {story_title, chapter_file} or None.
        Used by API routes as single source of truth for 'generating' status.
        """
        for job in self._jobs:
            if hasattr(job, 'get_currently_generating'):
                return job.get_currently_generating()
        return None
    
    async def start(self):
        """Main loop — runs forever within FastAPI lifespan."""
        self._running = True
        logger.info(f"[SCHEDULER] Started with {len(self._jobs)} jobs registered")
        
        # Restore state from DB
        self._restore_state()
        
        while self._running:
            try:
                # Wait for idle
                if not self._is_idle():
                    await asyncio.sleep(self.IDLE_CHECK_INTERVAL)
                    continue
                
                # Try each registered job for a task
                found_task = False
                for job in self._jobs:
                    task = await job.get_next_task()
                    if task:
                        found_task = True
                        await self._run_task(job, task)
                        break
                
                if not found_task:
                    # No tasks available — sleep longer
                    await asyncio.sleep(self.SLEEP_INTERVAL)
                    
            except asyncio.CancelledError:
                logger.info("[SCHEDULER] Shutdown requested")
                break
            except Exception as e:
                logger.error(f"[SCHEDULER] Unexpected error: {e}", exc_info=True)
                await asyncio.sleep(self.IDLE_CHECK_INTERVAL)
    
    def stop(self):
        """Signal the scheduler to stop."""
        self._running = False
        self._persist_state()
        logger.info("[SCHEDULER] Stopped")
    
    def _is_idle(self) -> bool:
        """Check: no on-demand TTS running + cooldown elapsed."""
        # Check if any on-demand TTS is active
        if self._generation_tasks_ref and len(self._generation_tasks_ref) > 0:
            logger.debug(f"[SCHEDULER] Not idle: {len(self._generation_tasks_ref)} active TTS tasks")
            return False
        
        # Check cooldown
        elapsed = time.time() - self._last_tts_activity
        if elapsed < self.COOLDOWN_SECONDS:
            logger.debug(f"[SCHEDULER] Not idle: cooldown {elapsed:.0f}s / {self.COOLDOWN_SECONDS}s")
            return False
        
        return True
    
    async def _run_task(self, job: BackgroundJobRunner, task: dict):
        """Execute a single task with error handling and state persistence."""
        self._current_job = job
        self._current_task = task
        task_desc = f"{job.job_name}: {task.get('story_title', '?')}/{task.get('chapter_file', '?')}"
        
        logger.debug(f"[SCHEDULER] Idle detected, starting: {task_desc}")
        self._update_db_state(job.job_name, "running", task)
        
        try:
            success = await job.execute_task(task)
            if success:
                logger.info(f"[SCHEDULER] Task completed: {task_desc}")
            else:
                logger.warning(f"[SCHEDULER] Task returned False: {task_desc}")
                
        except asyncio.CancelledError:
            logger.debug(f"[SCHEDULER] Task cancelled: {task_desc} (reason: user_request)")
            self._cancel_event.clear()
            
        except Exception as e:
            logger.error(f"[SCHEDULER] Task error: {task_desc}: {e}", exc_info=True)
            self._increment_error_count(job.job_name)
            
        finally:
            self._current_job = None
            self._current_task = None
            self._update_db_state(job.job_name, "idle", None)
            # Broadcast queue_update after task completes
            self._broadcast_queue_update()
    
    # --- Signal methods (called from server.py) ---
    
    def notify_tts_activity(self):
        """Called when any on-demand TTS request starts."""
        self._last_tts_activity = time.time()
        logger.debug("[SCHEDULER] TTS activity notified")
    
    def notify_tts_done(self):
        """Called when on-demand TTS stream finishes. Resets cooldown for KB2 resume."""
        # Don't reset _last_tts_activity here — let cooldown run naturally for KB2
        logger.debug("[SCHEDULER] TTS done notified")
    
    def request_pause(self):
        """KB3: Chat TTS needs Edge TTS — pause pre-gen IMMEDIATELY."""
        if self._current_job:
            logger.debug(f"[SCHEDULER] Pause requested (reason: chat_tts)")
        self._pause_event.clear()
    
    def request_resume(self):
        """KB3: Chat TTS done — resume pre-gen."""
        if not self._pause_event.is_set():
            logger.debug(f"[SCHEDULER] Resume requested")
        self._pause_event.set()
    
    def request_cancel(self):
        """KB2: User playing different chapter — cancel current pre-gen."""
        if self._current_job:
            logger.debug(f"[SCHEDULER] Cancel requested (reason: user_tts_different_chapter)")
        self._cancel_event.set()
        # Queue is re-prioritized — broadcast update
        self._broadcast_queue_update()
    
    async def check_pause_point(self):
        """Called by job workers EVERY CHUNK to check for pause/cancel signals.
        
        - If cancelled → raises CancelledError (job cleans up partial files)
        - If paused → blocks until resumed (preserves progress)
        """
        if self._cancel_event.is_set():
            self._cancel_event.clear()
            raise asyncio.CancelledError("Cancelled by user request")
        # Block if paused (clear = paused, set = running)
        await self._pause_event.wait()
    
    def is_generating(self, request_id: str) -> bool:
        """KB1: Check if pre-gen is working on this exact chapter."""
        if self._current_task:
            current_id = self._current_task.get("request_id", "")
            return current_id == request_id
        return False
    
    def is_running(self) -> bool:
        """Check if any job is currently executing."""
        return self._current_job is not None
    
    # --- Status / Monitoring ---
    
    def get_status(self) -> dict:
        """Return status for the current active job."""
        if self._current_job:
            job_status = self._current_job.get_status()
            job_status["scheduler_status"] = "running"
            return job_status
        return {"status": "idle", "scheduler_status": "idle"}
    
    def get_all_status(self) -> dict:
        """Return unified status for all jobs (for /api/background/status)."""
        jobs = []
        for job in self._jobs:
            status = job.get_status()
            status["is_active"] = (job == self._current_job)
            jobs.append(status)
        
        return {
            "status": "running" if self._current_job else "idle",
            "paused": not self._pause_event.is_set(),
            "jobs": jobs,
            # Flatten for simple frontend consumption
            **(self._current_job.get_status() if self._current_job else {}),
        }
    
    # --- Persistence ---
    
    def _update_db_state(self, job_name: str, status: str, task: dict | None):
        """Persist job state to DB for crash recovery."""
        try:
            db = get_db_session()
            state = db.query(BackgroundJobState).filter(
                BackgroundJobState.job_name == job_name
            ).first()
            
            if not state:
                state = BackgroundJobState(job_name=job_name)
                db.add(state)
            
            state.status = status
            state.last_run_at = time.time()
            state.current_task_info = json.dumps(task) if task else None
            db.commit()
        except Exception as e:
            logger.error(f"[SCHEDULER] Failed to persist state: {e}")
        finally:
            db.close()
    
    def _increment_error_count(self, job_name: str):
        """Increment error count for a job in DB."""
        try:
            db = get_db_session()
            state = db.query(BackgroundJobState).filter(
                BackgroundJobState.job_name == job_name
            ).first()
            if state:
                state.error_count = (state.error_count or 0) + 1
                db.commit()
        except Exception as e:
            logger.error(f"[SCHEDULER] Failed to update error count: {e}")
        finally:
            db.close()
    
    def _restore_state(self):
        """Restore job states from DB on startup."""
        try:
            db = get_db_session()
            states = db.query(BackgroundJobState).all()
            for state in states:
                    logger.debug(
                    f"[SCHEDULER] Restored state: {state.job_name} "
                    f"status={state.status} errors={state.error_count}"
                )
            db.close()
        except Exception as e:
            logger.error(f"[SCHEDULER] Failed to restore state: {e}")
    
    def _persist_state(self):
        """Persist all job states on shutdown."""
        for job in self._jobs:
            self._update_db_state(job.job_name, "idle", None)
    
    def _broadcast_queue_update(self):
        """Broadcast queue_update event via PregenStreamManager."""
        if not self._pregen_stream:
            return
        # Find the TTSPreGenJob to call preview_queue
        for job in self._jobs:
            if hasattr(job, 'preview_queue'):
                try:
                    queue = job.preview_queue(limit=10)
                    self._pregen_stream.broadcast({
                        "type": "queue_update",
                        "queue": queue,
                    })
                except Exception as e:
                    logger.error(f"[SCHEDULER] Failed to broadcast queue_update: {e}")
                break
