"""IconEdge Shared Memory MCP Tool Server.

Exposes durable entity operations to all FastAgent specialist agents:
- Leads & Prospects
- Ad Creatives & Variations
- Meta Ad Campaigns & Targeting
- Board Meetings & Multi-Agent Deliberations
"""
from __future__ import annotations

import json
import logging
import sys
import uuid
from pathlib import Path
from typing import Any, List, Optional

from mcp.server.fastmcp import Context, FastMCP

sys.path.insert(0, str(Path(__file__).parent.parent))

from services import shared_memory

logger = logging.getLogger("shared_memory_server")
mcp = FastMCP("IconEdgeSharedMemory")


# ── Prospects & Leads Tools ──────────────────────────────────────────────────


@mcp.tool()
def prospect_save(
    company_name: str,
    contact_name: str = "",
    email: str = "",
    phone: str = "",
    website: str = "",
    country: str = "Global",
    city: str = "",
    industry: str = "",
    source_agent: str = "LeadResearchAgent",
    status: str = "new",
    lead_score: int = 50,
    notes: str = "",
) -> dict:
    """Save or update a business lead/prospect into shared persistent memory.

    Use this tool whenever LeadResearchAgent discovers new businesses or OutreachAgent
    updates contact status.
    """
    try:
        return shared_memory.upsert_prospect(
            company_name=company_name,
            contact_name=contact_name or None,
            email=email or None,
            phone=phone or None,
            website=website or None,
            country=country or "Global",
            city=city or None,
            industry=industry or None,
            source_agent=source_agent,
            status=status,
            lead_score=lead_score,
            notes=notes or None,
        )
    except Exception as exc:
        logger.exception("Error saving prospect")
        return {"error": str(exc)}


@mcp.tool()
def prospect_search(
    query: str = "",
    status: str = "",
    country: str = "",
    industry: str = "",
    limit: int = 20,
) -> dict:
    """Search and query stored prospects in shared memory.

    Allows filtering by keyword, status ('new', 'qualified', 'contacted', 'converted'),
    country, or industry.
    """
    try:
        results = shared_memory.search_prospects(
            query=query or None,
            status=status or None,
            country=country or None,
            industry=industry or None,
            limit=limit,
        )
        return {"prospects": results, "count": len(results)}
    except Exception as exc:
        return {"error": str(exc)}


@mcp.tool()
def prospect_clear_all() -> dict:
    """Clear all prospects/leads from shared memory upon Mr. Owen's directive."""
    try:
        count = shared_memory.clear_all_prospects()
        return {"status": "success", "message": f"Successfully wiped {count} prospects from memory."}
    except Exception as exc:
        return {"error": str(exc)}


@mcp.tool()
def prospect_delete(prospect_id: int) -> dict:
    """Delete a single prospect from shared memory by ID."""
    try:
        success = shared_memory.delete_prospect(prospect_id=prospect_id)
        return {"status": "success" if success else "not_found", "prospect_id": prospect_id}
    except Exception as exc:
        return {"error": str(exc)}


# ── Ad Creatives Tools ───────────────────────────────────────────────────────


@mcp.tool()
def ad_creative_save(
    title: str,
    headline: str,
    body_copy: str,
    call_to_action: str = "Learn More",
    hook_type: str = "direct_offer",
    target_audience: str = "",
    image_prompt: str = "",
    status: str = "draft",
    variations_json: str = "",
) -> dict:
    """Save an ad copy and creative asset generated by Creative Agent.

    Includes headline, copy, hook angle ('pain_point', 'story', 'direct_offer', 'scarcity'),
    target audience, and image generation prompt.
    """
    try:
        variations = json.loads(variations_json) if variations_json else None
        return shared_memory.upsert_ad_creative(
            title=title,
            headline=headline,
            body_copy=body_copy,
            call_to_action=call_to_action,
            hook_type=hook_type,
            target_audience=target_audience or None,
            image_prompt=image_prompt or None,
            status=status,
            variations=variations,
        )
    except Exception as exc:
        return {"error": str(exc)}


@mcp.tool()
def ad_creative_list(status: str = "", target_audience: str = "", limit: int = 20) -> dict:
    """List stored ad creative assets from shared memory."""
    try:
        creatives = shared_memory.list_ad_creatives(
            status=status or None,
            target_audience=target_audience or None,
            limit=limit,
        )
        return {"creatives": creatives, "count": len(creatives)}
    except Exception as exc:
        return {"error": str(exc)}


# ── Ad Campaigns Tools ───────────────────────────────────────────────────────


@mcp.tool()
def campaign_save(
    name: str,
    objective: str = "OUTCOME_LEADS",
    status: str = "PAUSED",
    daily_budget: float = 0.0,
    targeting_json: str = "",
    creative_ids_json: str = "",
    meta_campaign_id: str = "",
) -> dict:
    """Save or update an ad campaign in shared memory.

    Note: All new campaigns start in 'PAUSED' state by default for safety.
    """
    try:
        targeting = json.loads(targeting_json) if targeting_json else None
        creative_ids = json.loads(creative_ids_json) if creative_ids_json else None
        return shared_memory.create_or_update_campaign(
            name=name,
            objective=objective,
            status=status,
            daily_budget=daily_budget,
            targeting=targeting,
            creative_ids=creative_ids,
            meta_campaign_id=meta_campaign_id or None,
        )
    except Exception as exc:
        return {"error": str(exc)}


@mcp.tool()
def campaign_list(status: str = "", limit: int = 20) -> dict:
    """List saved ad campaigns and their status from shared memory."""
    try:
        campaigns = shared_memory.list_campaigns(status=status or None, limit=limit)
        return {"campaigns": campaigns, "count": len(campaigns)}
    except Exception as exc:
        return {"error": str(exc)}


# ── Board Meeting Tools ──────────────────────────────────────────────────────


@mcp.tool()
def board_meeting_start(
    title: str = "Executive Board Meeting",
    agenda: str = "",
    participants: Any = None,
    participants_json: Any = None,
    meeting_id: str = "",
    topic: str = "",
) -> dict:
    """Start a board meeting session between Jarvis and specialist agents.
    
    participants: list of agent names (e.g. ['LeadResearchAgent', 'CreativeAgent', 'AdsAgent'])
    """
    try:
        if not meeting_id:
            meeting_id = f"meeting-{uuid.uuid4().hex[:8]}"
        if not agenda and topic:
            agenda = topic
        parsed_participants = []
        raw_p = participants if participants is not None else participants_json
        if isinstance(raw_p, list):
            parsed_participants = [str(p) for p in raw_p]
        elif isinstance(raw_p, str) and raw_p.strip():
            try:
                p = json.loads(raw_p)
                parsed_participants = [str(x) for x in p] if isinstance(p, list) else [str(p)]
            except Exception:
                parsed_participants = [x.strip() for x in raw_p.split(",") if x.strip()]
        
        if not parsed_participants:
            parsed_participants = ["Jarvis", "LeadResearchAgent", "CreativeAgent"]

        return shared_memory.start_board_meeting(
            meeting_id=meeting_id,
            title=title or "Executive Board Meeting",
            agenda=agenda or "Strategic Growth & Operations",
            participants=parsed_participants,
        )
    except Exception as exc:
        return {"error": str(exc)}


@mcp.tool()
def board_meeting_speak(
    speaker: str = "",
    message: str = "",
    statement: str = "",
    agent: str = "",
    meeting_id: str = "",
) -> dict:
    """Record an agent's deliberation statement or recommendation in a board meeting."""
    try:
        spk = speaker or agent or "SpecialistAgent"
        msg = message or statement or ""
        if not meeting_id:
            db = shared_memory.get_db_session()
            try:
                m = db.query(shared_memory.BoardMeetingModel).filter(
                    shared_memory.BoardMeetingModel.status == "in_progress"
                ).order_by(shared_memory.BoardMeetingModel.created_at.desc()).first()
                meeting_id = m.meeting_id if m else f"meeting-{uuid.uuid4().hex[:8]}"
            finally:
                db.close()

        return shared_memory.add_board_meeting_transcript(
            meeting_id=meeting_id,
            speaker=spk,
            message=msg,
        )
    except Exception as exc:
        return {"error": str(exc)}


@mcp.tool()
def board_meeting_conclude(
    action_plan: str = "",
    summary: str = "",
    meeting_id: str = "",
) -> dict:
    """Conclude a board meeting and record the final agreed action plan."""
    try:
        plan = action_plan or summary or "Action plan agreed and finalized."
        if not meeting_id:
            db = shared_memory.get_db_session()
            try:
                m = db.query(shared_memory.BoardMeetingModel).filter(
                    shared_memory.BoardMeetingModel.status == "in_progress"
                ).order_by(shared_memory.BoardMeetingModel.created_at.desc()).first()
                meeting_id = m.meeting_id if m else "active-meeting"
            finally:
                db.close()

        return shared_memory.conclude_board_meeting(
            meeting_id=meeting_id,
            action_plan=plan,
        )
    except Exception as exc:
        return {"error": str(exc)}


@mcp.tool()
def board_meeting_get(meeting_id: str) -> dict:
    """Retrieve full details, agenda, participants, and transcript of a board meeting."""
    try:
        meeting = shared_memory.get_board_meeting_details(meeting_id)
        if not meeting:
            return {"error": f"Board meeting '{meeting_id}' not found"}
        return meeting
    except Exception as exc:
        return {"error": str(exc)}


if __name__ == "__main__":
    mcp.run()
