"""Session management for fast-agent."""

from .formatting import (
    SessionEntrySummary,
    SessionListMode,
    build_session_entry_summaries,
    extract_session_title,
    format_history_summary,
    format_session_entries,
)
from .hydrator import (
    SessionHydrationPolicy,
    SessionHydrationResult,
    SessionHydrationWarning,
    SessionHydrator,
)
from .identity import SessionSaveContext, SessionSaveIdentity, resolve_session_for_save
from .session_manager import (
    ResumeSessionAgentsResult,
    Session,
    SessionInfo,
    SessionManager,
    apply_session_window,
    display_session_name,
    get_session_history_window,
    get_session_manager,
    is_session_pinned,
    reset_session_manager,
    summarize_session_histories,
)
from .snapshot import (
    SESSION_SNAPSHOT_SCHEMA_VERSION,
    SessionAgentSnapshot,
    SessionAnalysisSnapshot,
    SessionAttachmentRef,
    SessionCardProvenanceRef,
    SessionContinuationSnapshot,
    SessionDiagnosticSnapshot,
    SessionLineageSnapshot,
    SessionMetadataSnapshot,
    SessionModelOverlayRef,
    SessionRequestSettingsSnapshot,
    SessionSnapshot,
    SessionTimingSummarySnapshot,
    SessionUsageSummarySnapshot,
    capture_session_snapshot,
    clone_session_snapshot_for_fork,
    load_session_snapshot,
    session_info_from_snapshot,
    snapshot_from_session_info,
    synthesize_legacy_session_snapshot,
)
from .trace_export_errors import (
    InvalidSessionExportTargetError,
    SessionExportAgentNotFoundError,
    SessionExportAmbiguousAgentError,
    SessionExportNoAgentsError,
    SessionExportNotFoundError,
    SessionExportPrivacyFilterError,
    SessionExportReadError,
    SessionExportWriteError,
    TraceExportError,
    UnsupportedTraceExportFormatError,
)
from .trace_export_models import ExportFormat, ExportRequest, ExportResult, ResolvedSessionExport
from .trace_exporter import SessionTraceExporter

__all__ = [
    "ResumeSessionAgentsResult",
    "Session",
    "SessionInfo",
    "SessionManager",
    "apply_session_window",
    "display_session_name",
    "SessionListMode",
    "SessionEntrySummary",
    "build_session_entry_summaries",
    "extract_session_title",
    "format_history_summary",
    "format_session_entries",
    "get_session_history_window",
    "get_session_manager",
    "is_session_pinned",
    "reset_session_manager",
    "SessionSaveContext",
    "SessionSaveIdentity",
    "SessionHydrationPolicy",
    "SessionHydrationResult",
    "SessionHydrationWarning",
    "SessionHydrator",
    "SESSION_SNAPSHOT_SCHEMA_VERSION",
    "SessionAgentSnapshot",
    "SessionAnalysisSnapshot",
    "SessionAttachmentRef",
    "SessionCardProvenanceRef",
    "SessionContinuationSnapshot",
    "SessionDiagnosticSnapshot",
    "SessionLineageSnapshot",
    "SessionMetadataSnapshot",
    "SessionModelOverlayRef",
    "SessionRequestSettingsSnapshot",
    "SessionSnapshot",
    "SessionTimingSummarySnapshot",
    "SessionUsageSummarySnapshot",
    "capture_session_snapshot",
    "clone_session_snapshot_for_fork",
    "load_session_snapshot",
    "resolve_session_for_save",
    "session_info_from_snapshot",
    "snapshot_from_session_info",
    "summarize_session_histories",
    "synthesize_legacy_session_snapshot",
    "ExportFormat",
    "ExportRequest",
    "ExportResult",
    "InvalidSessionExportTargetError",
    "ResolvedSessionExport",
    "SessionExportAgentNotFoundError",
    "SessionExportAmbiguousAgentError",
    "SessionExportNoAgentsError",
    "SessionExportNotFoundError",
    "SessionExportPrivacyFilterError",
    "SessionExportReadError",
    "SessionExportWriteError",
    "SessionTraceExporter",
    "TraceExportError",
    "UnsupportedTraceExportFormatError",
]
