from __future__ import annotations

import json
import subprocess
from typing import TYPE_CHECKING

from fast_agent.plugins.operations import (
    check_plugin_updates,
    fetch_marketplace_plugins_with_source_sync,
    install_marketplace_plugin_sync,
)
from fast_agent.plugins.provenance import (
    compute_plugin_content_fingerprint,
    read_installed_plugin_source,
)

if TYPE_CHECKING:
    from pathlib import Path


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _init_repo(repo: Path) -> None:
    subprocess.run(["git", "init", str(repo)], check=True, capture_output=True, text=True)
    _git(repo, "config", "user.email", "tests@example.com")
    _git(repo, "config", "user.name", "Test User")


def _commit_all(repo: Path, message: str) -> str:
    _git(repo, "add", ".")
    _git(repo, "commit", "-m", message)
    return _git(repo, "rev-parse", "HEAD")


def _write_plugin(repo: Path) -> None:
    plugin_dir = repo / "plugins" / "finder"
    plugin_dir.mkdir(parents=True, exist_ok=True)
    (plugin_dir / "plugin.yaml").write_text(
        "schema_version: 1\n"
        "name: finder\n"
        "description: Finder plugin\n"
        "commands:\n"
        "  find:\n"
        "    description: Find things\n"
        "    handler: ./commands.py:find\n",
        encoding="utf-8",
    )
    (plugin_dir / "commands.py").write_text(
        "async def find(ctx):\n"
        "    return 'found'\n",
        encoding="utf-8",
    )


def _write_marketplace(repo: Path, path: Path) -> None:
    path.write_text(
        json.dumps(
            {
                "command_plugins": [
                    {
                        "name": "finder",
                        "repo_url": repo.as_posix(),
                        "repo_path": "plugins/finder",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )


def test_plugin_content_fingerprint_ignores_generated_bytecode(tmp_path: Path) -> None:
    plugin_dir = tmp_path / "finder"
    plugin_dir.mkdir()
    (plugin_dir / "plugin.yaml").write_text(
        "schema_version: 1\nname: finder\ncommands: {}\n",
        encoding="utf-8",
    )
    before = compute_plugin_content_fingerprint(plugin_dir)

    pycache = plugin_dir / "__pycache__"
    pycache.mkdir()
    (pycache / "commands.cpython-314.pyc").write_bytes(b"generated bytecode")

    assert compute_plugin_content_fingerprint(plugin_dir) == before


def test_plugin_update_ignores_unrelated_repo_commit_when_plugin_tree_same(
    tmp_path: Path,
) -> None:
    repo = tmp_path / "repo"
    _init_repo(repo)
    _write_plugin(repo)
    _commit_all(repo, "initial")
    marketplace_path = tmp_path / "marketplace.json"
    _write_marketplace(repo, marketplace_path)

    plugins, _ = fetch_marketplace_plugins_with_source_sync(marketplace_path.as_posix())
    destination_root = tmp_path / "plugins"
    install_dir = install_marketplace_plugin_sync(plugins[0], destination_root=destination_root)
    source, error = read_installed_plugin_source(install_dir)
    assert error is None
    assert source is not None
    assert source.installed_path_oid is not None

    (repo / "README.md").write_text("unrelated change\n", encoding="utf-8")
    _commit_all(repo, "unrelated")

    updates = check_plugin_updates(destination_root=destination_root)

    assert len(updates) == 1
    assert updates[0].status == "up_to_date"
    assert updates[0].detail == "already up to date"
